In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow
from tensorflow import keras
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML Projects/Afame Technologies Project/Customer Churn Prediction/Churn_Modelling.csv')

In [ ]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
3674,3675,15749693,Ugonnatubelum,658,France,Female,32,9,0.00,2,1,0,156774.75,0
8439,8440,15692931,Hsing,670,France,Male,22,2,114991.45,1,1,1,37392.56,0
1481,1482,15583748,McGuigan,592,Spain,Male,38,8,0.00,2,1,0,180426.20,0
4148,4149,15758306,T'an,654,France,Male,32,6,0.00,2,1,1,137898.57,0
2167,2168,15780846,Redding,787,France,Male,33,1,126588.81,2,0,1,62163.53,0
9901,9902,15802909,Hu,706,Germany,Female,56,3,139603.22,1,1,1,86383.61,0
8775,8776,15812720,Hooker,807,Germany,Male,37,10,130110.45,2,0,1,172097.95,0
8978,8979,15765857,Genovesi,623,Spain,Male,41,2,142412.13,1,1,0,28778.98,0
4744,4745,15582849,McIntosh,757,France,Female,51,1,0.00,1,1,1,22835.13,1
1605,1606,15640865,Romano,636,Germany,Female,31,9,80844.69,2,1,1,74641.90,0

In [ ]:
df.drop(columns = ['RowNumber','CustomerId','Surname'], inplace= True)

In [ ]:
df.sample(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5120,663,France,Male,26,5,141462.13,1,1,0,440.20,0
8061,477,Spain,Male,31,9,0.00,2,0,1,184061.17,0
2762,719,Germany,Male,28,3,106070.29,2,1,1,183893.31,0
9656,696,Germany,Male,32,4,84421.62,1,0,1,52314.71,0
8963,741,France,Male,52,1,171236.30,2,0,0,21834.40,1
5241,574,France,Male,41,1,0.00,2,0,0,70550.00,0
987,569,Spain,Male,34,0,151839.26,1,1,0,102299.81,1
2400,711,Germany,Male,34,4,133467.77,2,1,1,42976.64,0
1801,452,France,Male,30,7,112935.87,1,1,1,99017.34,0
3719,850,France,Female,62,1,124678.35,1,1,0,70916.00,1

In [ ]:
new_df_1 = pd.get_dummies(df, columns = ['Geography', 'Gender'], drop_first = True, dtype = 'int')

In [ ]:
new_df_1.sample(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
5638,729,38,7,0.00,2,0,0,45779.90,0,0,0,0
8345,568,46,3,0.00,2,1,1,29372.62,0,0,1,0
7981,599,38,9,89111.63,1,0,0,157239.60,0,1,0,1
4098,637,32,5,0.00,1,0,0,148769.08,0,0,0,1
9456,639,39,6,150555.83,1,1,0,30414.17,0,0,0,1
7429,685,43,6,117302.62,1,0,0,68701.73,0,0,1,0
6441,514,45,1,178827.79,1,1,0,60375.18,0,0,0,1
7251,724,31,9,138166.30,1,1,0,12920.43,0,1,0,1
481,525,23,5,0.00,2,1,0,160249.10,0,0,0,0
5024,745,44,0,119638.21,1,1,1,34265.08,1,1,0,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x = new_df_1.drop(columns = ['Exited'])
y = new_df_1['Exited']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 2)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.fit_transform(x_test)

In [ ]:
x_train_scaled.shape, x_test_scaled.shape

((8000, 11), (2000, 11))

In [ ]:
model = Sequential()
model.add(Dense(12, activation = 'relu', input_dim = 11))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(128, activation = 'relu'))
model.add(Dense(256, activation = 'relu'))
model.add(Dense(512, activation = 'relu'))
model.add(Dense(1024, activation = 'relu'))
model.add(Dense(1, activation = 'relu'))

In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(x_train_scaled, y_train, epochs = 100)

Epoch 1/100
250/250 [==============================] - 6s 16ms/step - loss: 0.5114 - accuracy: 0.7970
Epoch 2/100
250/250 [==============================] - 5s 18ms/step - loss: 0.4899 - accuracy: 0.8130
Epoch 3/100
250/250 [==============================] - 5s 21ms/step - loss: 0.4535 - accuracy: 0.8305
Epoch 4/100
250/250 [==============================] - 4s 16ms/step - loss: 0.4122 - accuracy: 0.8350
Epoch 5/100
250/250 [==============================] - 4s 16ms/step - loss: 0.4262 - accuracy: 0.8314
Epoch 6/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3978 - accuracy: 0.8376
Epoch 7/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3822 - accuracy: 0.8453
Epoch 8/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3785 - accuracy: 0.8497
Epoch 9/100
250/250 [==============================] - 5s 18ms/step - loss: 0.3552 - accuracy: 0.8497
Epoch 10/100
250/250 [==============================] - 5s 21ms/step - loss: 0.3558 - accuracy: 0.8526
Epoch 11/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3546 - accuracy: 0.8560
Epoch 12/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3636 - accuracy: 0.8551
Epoch 13/100
250/250 [==============================] - 6s 24ms/step - loss: 0.3563 - accuracy: 0.8590
Epoch 14/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3490 - accuracy: 0.8550
Epoch 15/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3455 - accuracy: 0.8620
Epoch 16/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3653 - accuracy: 0.8597
Epoch 17/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3903 - accuracy: 0.8426
Epoch 18/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3840 - accuracy: 0.8486
Epoch 19/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3630 - accuracy: 0.8504
Epoch 20/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3789 - accuracy: 0.8587
Epoch 21/100
250/250 [==============================] - 4s 17ms/step - loss: 0.4161 - accuracy: 0.8478
Epoch 22/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3991 - accuracy: 0.8509
Epoch 23/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3404 - accuracy: 0.8609
Epoch 24/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3372 - accuracy: 0.8640
Epoch 25/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3372 - accuracy: 0.8655
Epoch 26/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3343 - accuracy: 0.8669
Epoch 27/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3702 - accuracy: 0.8558
Epoch 28/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3804 - accuracy: 0.8583
Epoch 29/100
250/250 [==============================] - 4s 15ms/step - loss: 0.4134 - accuracy: 0.8499
Epoch 30/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3690 - accuracy: 0.8584
Epoch 31/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3640 - accuracy: 0.8587
Epoch 32/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3733 - accuracy: 0.8501
Epoch 33/100
250/250 [==============================] - 5s 19ms/step - loss: 0.4286 - accuracy: 0.8422
Epoch 34/100
250/250 [==============================] - 5s 21ms/step - loss: 0.3576 - accuracy: 0.8604
Epoch 35/100
250/250 [==============================] - 4s 16ms/step - loss: 0.4038 - accuracy: 0.8372
Epoch 36/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3591 - accuracy: 0.8560
Epoch 37/100
250/250 [==============================] - 6s 24ms/step - loss: 0.3731 - accuracy: 0.8549
Epoch 38/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3667 - accuracy: 0.8564
Epoch 39/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3452 - accuracy: 0.8620
Epoch 40/100
250/250 [==============================] - 5s 20ms/step - loss: 0.4264 - accuracy: 0.8365
Epoch 41/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3627 - accuracy: 0.8544
Epoch 42/100
250/250 [==============================] - 6s 24ms/step - loss: 0.3436 - accuracy: 0.8651
Epoch 43/100
250/250 [==============================] - 7s 26ms/step - loss: 0.3382 - accuracy: 0.8631
Epoch 44/100
250/250 [==============================] - 4s 17ms/step - loss: 0.4005 - accuracy: 0.8460
Epoch 45/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3738 - accuracy: 0.8610
Epoch 46/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3460 - accuracy: 0.8627
Epoch 47/100
250/250 [==============================] - 5s 21ms/step - loss: 0.3364 - accuracy: 0.8630
Epoch 48/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3335 - accuracy: 0.8656
Epoch 49/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3278 - accuracy: 0.8658
Epoch 50/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3274 - accuracy: 0.8686
Epoch 51/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3543 - accuracy: 0.8549
Epoch 52/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3333 - accuracy: 0.8660
Epoch 53/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3382 - accuracy: 0.8631
Epoch 54/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3671 - accuracy: 0.8614
Epoch 55/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3560 - accuracy: 0.8634
Epoch 56/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3634 - accuracy: 0.8604
Epoch 57/100
250/250 [==============================] - 6s 24ms/step - loss: 0.3431 - accuracy: 0.8644
Epoch 58/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3291 - accuracy: 0.8637
Epoch 59/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3424 - accuracy: 0.8646
Epoch 60/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3325 - accuracy: 0.8652
Epoch 61/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3327 - accuracy: 0.8676
Epoch 62/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3422 - accuracy: 0.8602
Epoch 63/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3349 - accuracy: 0.8639
Epoch 64/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3248 - accuracy: 0.8650
Epoch 65/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3361 - accuracy: 0.8661
Epoch 66/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3282 - accuracy: 0.8640
Epoch 67/100
250/250 [==============================] - 5s 21ms/step - loss: 0.4123 - accuracy: 0.8385
Epoch 68/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3536 - accuracy: 0.8544
Epoch 69/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3282 - accuracy: 0.8639
Epoch 70/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3269 - accuracy: 0.8668
Epoch 71/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3174 - accuracy: 0.8681
Epoch 72/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3252 - accuracy: 0.8659
Epoch 73/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3377 - accuracy: 0.8691
Epoch 74/100
250/250 [==============================] - 5s 22ms/step - loss: 0.3480 - accuracy: 0.8604
Epoch 75/100
250/250 [==============================] - 4s 18ms/step - loss: 0.3539 - accuracy: 0.8640
Epoch 76/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3283 - accuracy: 0.8640
Epoch 77/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3492 - accuracy: 0.8686
Epoch 78/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3379 - accuracy: 0.8675
Epoch 79/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3946 - accuracy: 0.8581
Epoch 80/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3773 - accuracy: 0.8583
Epoch 81/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3460 - accuracy: 0.8605
Epoch 82/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3608 - accuracy: 0.8652
Epoch 83/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3570 - accuracy: 0.8621
Epoch 84/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3412 - accuracy: 0.8665
Epoch 85/100
250/250 [==============================] - 5s 21ms/step - loss: 0.3537 - accuracy: 0.8683
Epoch 86/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3968 - accuracy: 0.8620
Epoch 87/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3364 - accuracy: 0.8675
Epoch 88/100
250/250 [==============================] - 6s 22ms/step - loss: 0.3666 - accuracy: 0.8654
Epoch 89/100
250/250 [==============================] - 4s 16ms/step - loss: 0.4145 - accuracy: 0.8586
Epoch 90/100
250/250 [==============================] - 4s 17ms/step - loss: 0.3746 - accuracy: 0.8674
Epoch 91/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3592 - accuracy: 0.8656
Epoch 92/100
250/250 [==============================] - 5s 20ms/step - loss: 0.3306 - accuracy: 0.8681
Epoch 93/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3317 - accuracy: 0.8665
Epoch 94/100
250/250 [==============================] - 4s 15ms/step - loss: 0.3281 - accuracy: 0.8675
Epoch 95/100
250/250 [==============================] - 6s 23ms/step - loss: 0.3528 - accuracy: 0.8665
Epoch 96/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3396 - accuracy: 0.8668
Epoch 97/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3192 - accuracy: 0.8679
Epoch 98/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3337 - accuracy: 0.8686
Epoch 99/100
250/250 [==============================] - 5s 19ms/step - loss: 0.3844 - accuracy: 0.8565
Epoch 100/100
250/250 [==============================] - 4s 16ms/step - loss: 0.3639 - accuracy: 0.8627

In [ ]:
import numpy as np
y_log = model.predict(x_test_scaled)

y_pred = np.where(y_log >0.5, 1, 0)

accuracy_score(y_test, y_pred)

63/63 [==============================] - 0s 4ms/step

0.8325